### ISSUE TITLE
The macpath module is deprecated and will be removed in Python 3.8

### ISSUE THREAD

**Issue by MarcSkovMadsen** [stackp/Droopy#27]
![image](https://user-images.githubusercontent.com/42288570/67754130-307a2500-fa36-11e9-8cab-e9761d43c498.png)

Thanks for a great product :-)

**Comment by mitsakosgr** [comment]
You can try replacing "macpath" with "os.tools" in droopy file.

**Comment by developmentMen** [comment]
whit python3 on ubuntu run perfect

![Captura de pantalla (20)](https://user-images.githubusercontent.com/59296510/100298325-9bff3080-2f6f-11eb-9f5a-481ef761b4de.png)

**Comment by stackp** [comment]
Thanks!
