### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by TeCoEd** [stackp/Droopy#9]
great web server and so easy to set up.  Sometimes the files I receive will not open and have a permission error, have you come across this before?

**Comment by stackp** [comment]
Hi, you can set the permissions for saved files with the ``--chmod`` option. For instance:
```
droopy --chmod 777
```
Best,
Pierre

**Comment by TeCoEd** [comment]
Brilliant. Many thanks. 


Dan Aldred

-------- Original message --------
